;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
	delete-region
	kill-region
	))

(setq mc/cmds-to-run-once
      '(
	find-file
	markdown-exdent-or-delete
	nxml-electric-slash
	ruby-end-space
	))
